import Head from "next/head";
import About from "../components/About";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>eCommerce App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main style={{ height: "70vh" }}>
          <h1>Welcome to Home Page</h1>
        </main>
        {/* <About /> */}
      </div>
    </Layout>
  );
}
