import Head from "next/head";
import About from "../components/About";
import Hero from "../components/Hero";
import Layout from "../components/Layout";
import Service from "../components/Service";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>eCommerce App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Hero />
          <Service />
        </main>
        {/* <About /> */}
      </div>
    </Layout>
  );
}
